apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-gateway.fullname" . }}
  labels:
    {{- include "fhir-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fhir-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}-fhir-gateway
