{{- if and (not (index .Values "postgresql" "enabled")) (not .Values.sinks.postgres.external.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "postgres-secret"  }}
  labels:
    {{- include "fhir-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: fhir-gateway
type: Opaque
data:
  postgresql-password: {{ .Values.sinks.postgres.external.password | b64enc | quote }}
{{- end -}}
